# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5800300610a7c367bae39ba7a6ff6bf760aa65dff2b344f31f1a97953287575eb050c3b2d843f8fbee2faa0462004a8c9497d38e74a2fda090ed8065ef87e0b
  secret_token: c377efad74336cecca0cfef9cc4688525a878356c41b85ad0902bc867372884837740374ade2e87a4fb579c8f04ceba45cc67789e32d6e51ff3c7272cc5d5222

test:
  secret_key_base: b5554e92bc53cfbb53cf9d11acf1475c0f675f6539c96edf96e0dcd60924bf0fcc12afc9d3f6c0da571c10ac48665afdef0e00e8022cbc55f5b333ca8f9b0ed2
  secret_token: c377efad74336cecca0cfef9cc4688525a878356c41b85ad0902bc867372884837740374ade2e87a4fb579c8f04ceba45cc67789e32d6e51ff3c7272cc5d5222

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_TOKEN"] %>
